services:

  api_server:
    # platform: linux/amd64
    image: chatbot_server:1.0.0
    build: ./api_server
    volumes:
      - hf_cache:/root/.cache/huggingface
    env_file:
      - .env
    depends_on:
      - redis_listener
      - redis
      - qdrant
    environment:
      # ===== NGINX
      NGINX_URL: http://nginx:8080

      # ===== REDIS
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_MEMORY: 0
      REDIS_DB_VALIDATOR: 1
      REDIS_DECODE_RESPONSES: true
      REDIS_TTL_SECONDS: 900

      # ===== QDRANT
      QDRANT_URL: http://qdrant:6333
      TOP_K_DENSE: 8
      TOP_K_SPARSE: 8
      LIMIT_N_HYBRID_CAPS: 3
      LIMIT_N_HYBRID_TEXT: 4

      # ===== EMBEDDINGS
      DENSE_EMBEDDER: sentence-transformers/all-MiniLM-L6-v2
      SPARSE_EMBEDDER: Qdrant/bm25
      EMBEDDING_BATCH_SIZE: 16
      EMBEDDING_N_DIMENSIONS: 384

      # ===== CONSTRAINTS
      MAX_AUDIO_SIZE: 60000
      MAX_TEXT_SIZE: 150
      MAX_MESSAGE_HISTORY_MEMORY: 6

      # ===== MODEL SOURCES (Enums → MUST match exactly)
      LLM_SOURCE: groq
      GUARD_SOURCE: huggingface

      # ===== OLLAMA
      OLLAMA_HOST: http://host.docker.internal:11434

      # ===== LLMs
      GROQ_LLM: meta-llama/llama-4-scout-17b-16e-instruct
      GEMINI_LLM: gemma-3-1b-it
      OLLAMA_LLM: llama3:8b

      # ===== MULTIMODAL
      GEMINI_MULTIMODAL: gemini-2.5-flash

      # ===== RATES FOR LLMs
      INPUT_RATE_PER_M: 0.11
      OUTPUT_RATE_PER_M: 0.34

      # ===== RATES FOR USER LIMIT
      MAX_REQUESTS_PER_WINDOW: 10
      WINDOW_SECONDS: 1800

      # ===== GUARD
      GUARD_PROBABILITY_THRESHOLD: 0.2
      GROQ_PROMPT_GUARD: meta-llama/llama-prompt-guard-2-86m
      HF_PROMPT_GUARD: meta-llama/Llama-Prompt-Guard-2-86M

  redis_listener:
    # platform: linux/amd64
    image: chatbot_redis_listener:1.0.0
    build: ./redis_listener
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      # ===== REDIS
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_MEMORY: 0
      REDIS_DECODE_RESPONSES: true
      REDIS_TIMEOUT_SECONDS: 5

  nginx:
    # platform: linux/amd64
    image: nginx:1.29.7-alpine-perl
    ports:
      - "8082:8080"
    volumes:
      - ./nginx/nginx_monolith.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_server

  redis:
    # platform: linux/amd64
    image: redis/redis-stack:7.4.0-v8
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--notify-keyspace-events Ex
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  qdrant:
    # platform: linux/amd64
    image: qdrant/qdrant:v1.17
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
  hf_cache: