# Configuration for embedding model with HF
EMBEDDING_MODEL: "all-MiniLM-L6-v2"
EMBEDDING_BATCH_SIZE: 16
EMBEDDING_N_DIMENSIONS: 384

# Configuration for my large language model with OLLAMA
LLM_ANSWER_MODEL: "qwen3:8b"
LLM_VERIFY_MODEL: "qwen2.5:7b"

# Configuration for vector database
TOP_K: 5
THRESHOLD: 0.5