# Configuration for embedding model with HF
EMBEDDING_MODEL: "all-MiniLM-L6-v2"
EMBEDDING_BATCH_SIZE: 16
EMBEDDING_N_DIMENSIONS: 384

# Configuration for LLM
LLM_SOURCE: "groq"
LLM_GENERATOR_MODEL_GEMINI: "gemini-3-flash-preview"
LLM_VERIFY_MODEL_GEMINI: "gemini-3-flash-preview"
LLM_GENERATOR_MODEL_OLLAMA: "qwen3:8b"
LLM_VERIFY_MODEL_OLLAMA: "qwen3:8b"
LLM_GENERATOR_MODEL_GROQ: "llama-3.1-8b-instant"
LLM_VERIFY_MODEL_GROQ: "llama-3.1-8b-instant"

# Configuration for vector database
TOP_K: 12
THRESHOLD: 0.5