events {}

http {

    limit_req_zone $binary_remote_addr zone=per_minute:10m rate=1000r/m;

    upstream rerank_cluster {
        server rerank_server_1:8002;
        server rerank_server_2:8002;
        server rerank_server_3:8002;
    }

    upstream main_server {
        server api_server:8000;
    }

    server {
        listen 8080;

        # --- Reranker ---
        location = /rerank {
            proxy_pass http://rerank_cluster;
        }

        location /rerank/ {
            proxy_pass http://rerank_cluster;
        }

        # --- Main API (catches everything else) ---
        location / {
            limit_req zone=per_minute burst=50 nodelay;
            limit_req_status 429;
            proxy_pass http://main_server;
            proxy_set_header Host            $host;
            proxy_set_header X-Real-IP       $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}