events {}

http {

    upstream rag_cluster {
        server rag_server_1:8002;
        server rag_server_2:8002;
        server rag_server_3:8002;
    }

    server {
        listen 8080;

        location /search {
            proxy_pass http://rag_cluster;
        }

        location /health {
            proxy_pass http://rag_cluster;
        }
    }

}