events {}

http {

    upstream rerank_cluster {
        server rerank_server_1:8002;
        server rerank_server_2:8002;
        server rerank_server_3:8002;
    }

    server {
        listen 8080;

        location /rerank {
            proxy_pass http://rerank_cluster;
        }

        location /health {
            proxy_pass http://rerank_cluster;
        }
    }

}